a=0,b=2*pi;
x=linspace(a,b,100);
f='sin(x.*(1-x))';
plot(x,eval(f),x,0*x,':');
grid on;
xlabel('x');
ylabel('y');
z=ginput(1);
[zr,fr]=fzero(f,z(1));
hold on;
plot(zr,fr,'r*',z(1),z(2),'g*');